name = "SGC Functions";
picture = "icon.svg";
logo = "icon.svg";
logoOver = "icon.svg";
tooltip = "SGCFunctions";
tooltipOwned = "SGCFunctions";
overview = "Reusable SQF helper functions for Arma 3 mission makers.";
author = "SGC";
overviewPicture = "icon.svg";
