name = "SGC Functions";
picture = "icon.jpg";
logo = "icon.jpg";
logoOver = "icon.jpg";
tooltip = "SGCFunctions";
tooltipOwned = "SGCFunctions";
overview = "Reusable SQF helper functions for Arma 3 mission makers.";
author = "SGC";
overviewPicture = "icon.jpg";
